steps:
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       set -e
  #       echo "Starting deployment..."
  #       gcloud config list
  #       gcloud functions deploy get-product-recommendation `
  #         --runtime=python310 `
  #         --trigger-http `
  #         --entry-point=main `
  #         --region=us-central1 `
  #         --allow-unauthenticated `
  #         --source=. `
  #         --verbosity=debug
  #step1
  - name: 'python:3.10'
    id: 'Install dependencies and packages'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y build-essential python3-dev
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'get-product-recommendation'
      - '--runtime=python310'
      - '--trigger-http'
      - '--entry-point=main'
      - '--region=us-central1'
      # - '--memory=2Gib'
      - '--allow-unauthenticated'
    # waitFor: ['test']

options:
  logging: CLOUD_LOGGING_ONLY
  machine_type: 'E2_HIGHCPU_8'
  # env:
  #   - 'GOOGLE_CLOUD_PROJECT=carbon-beanbag-452610-q6'
  #   - 'GOOGLE_CLOUD_REGION=us-central1' 
timeout: "900s"