name: Trigger Cloud Build on Push

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Trigger Cloud Build
      uses: google-github-actions/cloud-build@v2
      with:
        project_id: carbon-beanbag-452610-q6
        config: cloudbuild.yaml
